# Generated by Django 4.2.6 on 2023-11-25 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager_msa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='favorite',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='serie',
            name='favorite',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='movie',
            name='watch',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='serie',
            name='complete',
            field=models.BooleanField(default=0),
        ),
    ]
