# Generated by Django 4.2.6 on 2023-11-28 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager_msa', '0003_remove_movie_favorite_remove_serie_favorite_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='rating',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='serie',
            name='rating',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
